// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StockMarketBuyingGuide.Api.Infrastructure;

#nullable disable

namespace StockMarketBuyingGuide.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StockMarketBuyingGuide.Api.Infrastructure.Entities.NewsSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Headline")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RelatedTickers")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.ToTable("NewsSnapshots");
                });

            modelBuilder.Entity("StockMarketBuyingGuide.Api.Infrastructure.Entities.PerformanceTracking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CurrentPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<int>("DaysAfterPick")
                        .HasColumnType("integer");

                    b.Property<Guid>("PickId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PickId");

                    b.ToTable("PerformanceTrackings");
                });

            modelBuilder.Entity("StockMarketBuyingGuide.Api.Infrastructure.Entities.RecommendationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("AsOfDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<bool>("IsBacktest")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("SimulationJobId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AsOfDate");

                    b.HasIndex("SimulationJobId");

                    b.ToTable("RecommendationRuns");
                });

            modelBuilder.Entity("StockMarketBuyingGuide.Api.Infrastructure.Entities.SimulationDayResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CapitalAfter")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("CapitalBefore")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("TradingDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("RunId");

                    b.ToTable("SimulationDayResults");
                });

            modelBuilder.Entity("StockMarketBuyingGuide.Api.Infrastructure.Entities.SimulationJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<decimal?>("FinalCapital")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<decimal>("StartingCapital")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StartDate", "EndDate", "StartingCapital");

                    b.ToTable("SimulationJobs");
                });

            modelBuilder.Entity("StockMarketBuyingGuide.Api.Infrastructure.Entities.StockPick", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PriceAtRecommendation")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("Reasoning")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.ToTable("StockPicks");
                });

            modelBuilder.Entity("StockMarketBuyingGuide.Api.Infrastructure.Entities.StockSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("High52Week")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("Low52Week")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("PctChange")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("SnapshotDate")
                        .HasColumnType("date");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "Ticker");

                    b.ToTable("StockSnapshots");
                });

            modelBuilder.Entity("StockMarketBuyingGuide.Api.Infrastructure.Entities.NewsSnapshot", b =>
                {
                    b.HasOne("StockMarketBuyingGuide.Api.Infrastructure.Entities.RecommendationRun", "Run")
                        .WithMany("NewsSnapshots")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("StockMarketBuyingGuide.Api.Infrastructure.Entities.PerformanceTracking", b =>
                {
                    b.HasOne("StockMarketBuyingGuide.Api.Infrastructure.Entities.StockPick", "Pick")
                        .WithMany("PerformanceRecords")
                        .HasForeignKey("PickId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pick");
                });

            modelBuilder.Entity("StockMarketBuyingGuide.Api.Infrastructure.Entities.RecommendationRun", b =>
                {
                    b.HasOne("StockMarketBuyingGuide.Api.Infrastructure.Entities.SimulationJob", "SimulationJob")
                        .WithMany("Runs")
                        .HasForeignKey("SimulationJobId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SimulationJob");
                });

            modelBuilder.Entity("StockMarketBuyingGuide.Api.Infrastructure.Entities.SimulationDayResult", b =>
                {
                    b.HasOne("StockMarketBuyingGuide.Api.Infrastructure.Entities.SimulationJob", "Job")
                        .WithMany("DayResults")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockMarketBuyingGuide.Api.Infrastructure.Entities.RecommendationRun", "Run")
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("Run");
                });

            modelBuilder.Entity("StockMarketBuyingGuide.Api.Infrastructure.Entities.StockPick", b =>
                {
                    b.HasOne("StockMarketBuyingGuide.Api.Infrastructure.Entities.RecommendationRun", "Run")
                        .WithMany("StockPicks")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("StockMarketBuyingGuide.Api.Infrastructure.Entities.StockSnapshot", b =>
                {
                    b.HasOne("StockMarketBuyingGuide.Api.Infrastructure.Entities.RecommendationRun", "Run")
                        .WithMany("StockSnapshots")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("StockMarketBuyingGuide.Api.Infrastructure.Entities.RecommendationRun", b =>
                {
                    b.Navigation("NewsSnapshots");

                    b.Navigation("StockPicks");

                    b.Navigation("StockSnapshots");
                });

            modelBuilder.Entity("StockMarketBuyingGuide.Api.Infrastructure.Entities.SimulationJob", b =>
                {
                    b.Navigation("DayResults");

                    b.Navigation("Runs");
                });

            modelBuilder.Entity("StockMarketBuyingGuide.Api.Infrastructure.Entities.StockPick", b =>
                {
                    b.Navigation("PerformanceRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
